// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpvzJe55H1ckCeURfx2eDjMMEpCT2_qMQ',
    appId: '1:264584022798:web:3f7c242931fa89ecebe55f',
    messagingSenderId: '264584022798',
    projectId: 'e-commerce-a36e1',
    authDomain: 'e-commerce-a36e1.firebaseapp.com',
    storageBucket: 'e-commerce-a36e1.appspot.com',
    measurementId: 'G-D8CD8V06DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAaoYIwsV5GiYsF8BaNIAaM5rRhWlIV6A',
    appId: '1:264584022798:android:adf983594caf0211ebe55f',
    messagingSenderId: '264584022798',
    projectId: 'e-commerce-a36e1',
    storageBucket: 'e-commerce-a36e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkcBFnw0KBfNC5g1zg6NOSIOwSo4wyrho',
    appId: '1:264584022798:ios:b22a1645416ce510ebe55f',
    messagingSenderId: '264584022798',
    projectId: 'e-commerce-a36e1',
    storageBucket: 'e-commerce-a36e1.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkcBFnw0KBfNC5g1zg6NOSIOwSo4wyrho',
    appId: '1:264584022798:ios:e09e5f2c08f939c2ebe55f',
    messagingSenderId: '264584022798',
    projectId: 'e-commerce-a36e1',
    storageBucket: 'e-commerce-a36e1.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
